# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tperiod',
        ),
    ]
